---
- name: Shell
  hosts: [linux_all]
  tasks:

  - name: Restart_services
    shell: |
      systemctl restart network
      /bin/systemctl restart openvpnas.service
    register: command_result
    async: 1
    poll: 0
    ignore_errors: true
  
  - name: wait
    local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=10
